### PR TITLE
First commit for a few more methods and set_attr function

### PR DESCRIPTION
**Pull request by itdependsnetworks**
Not push ready, but figured would take any comments before I create a few more methods. 

Just out of curiosity, what was the issue with adding to core? I would suspect that would want to break this out into smaller modules? Any thought into making this into a pypi library separate from ansible, and have ansible just just call said library.

### CODE REVIEW

**Comment by xoanmi** [comment]
Hi!

The changes look fine for me.

I tried to add the module to the ansible modules extras a year ago but they require several changes and I didn't have time to implement it.

Thanks,

**Comment by itdependsnetworks** [comment]
What specifically?

**Comment by xoanmi** [comment]
Honestly nothing important: python version, format (PIP8), use of requests, etc...

**Comment by xoanmi** [comment]
I've cerated a new pool request to ansible core: https://github.com/ansible/ansible/pull/27904

:)

**Pull request merged**
