### PR TITLE
Placeholder PR

### PR DESCRIPTION
**Pull request by itdependsnetworks**
So I see we are getting out of sync :) 

@brampling 
There was an issue with with add_host in the PR before me, you were no longer able to create a host record without specifying network or range. Let me know if these changes make sense

### CODE REVIEW

**Comment by brampling** [comment]
I introduced that issue when I added the range functionality and I didn't test the address functionality after I made the changes. I just cloned your branch and tested it and add_host is working for address and network but not for a range (with start_addr and end_addr). It's not erroring out, it's just not working:

PLAY RECAP **********************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=0  

I'm going to look into it some more.

**Comment by itdependsnetworks** [comment]
So this could potentially be an issue with indents. If I recall correctly near the start_addr/end_addr there was usage of tabs. I removed them and put back I as I thought correctly, but easily could have messed it up.

**Comment by itdependsnetworks** [comment]
Also, from my side everything looks good, with notable exception being explained above :) I think the point I left it off in previous PR was not a good state tbh.

**Comment by xoanmi** [comment]
Hi guys! I'm out of office for next couple of weeks and I can't check it properly.
I hope you are testing the code to ensure all functions are working as expected :)

**Pull request merged**
